In [2]:
# 

In [3]:
import pandas as pd
pd_list = pd.Series([5000,6000,6500,6500],
                    index=["americano","latte","cappuccino","mocha"])

print(pd_list)


americano     5000
latte         6000
cappuccino    6500
mocha         6500
dtype: int64


In [4]:
print("시리즈의 값:", pd_list.values)   #변수.values -> 시리즈 값만 출력
print("시리즈의 인덱스 값:",pd_list.index)  #변수.index -> 시리즈의 인덱스 값만 출력 

시리즈의 값: [5000 6000 6500 6500]
시리즈의 인덱스 값: Index(['americano', 'latte', 'cappuccino', 'mocha'], dtype='object')


In [5]:
#DataFrame  이차원 리스트 : 행렬의 구조와 매우 유사 
_values = [[1,2,3],[4,5,6],[7,8,9]]
_index = ['a','b','c']
_columns = ['A','B','C']

pd_dataframe = pd.DataFrame(data=_values, index=_index, columns=_columns) 
# = 로 이어주는 이유: 순서 바뀌지 않게..

print(pd_dataframe)

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9


In [6]:
print("df의 인덱스 값:", pd_dataframe.index)
print("df의 컬럼 값:",pd_dataframe.columns)
print("df의 프레임 값:",pd_dataframe.values)

df의 인덱스 값: Index(['a', 'b', 'c'], dtype='object')
df의 컬럼 값: Index(['A', 'B', 'C'], dtype='object')
df의 프레임 값: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
list_data_2={
    "name":["A","B","C"],
    "sex":["m","f","f"],
    "phone":["010-3126-9994","010-6523-1786","010-0620-0210"]

}       #데이터형 딕셔너리는 key:value로 데이터가 구성되어있기 때문에 key 값이 columns의 값으로 지정
 #절대 모듈이름을 파일명으로 저장하지 말것 
pd_dataframe_3=pd.DataFrame(list_data_2)

print(pd_dataframe_3)

  name sex          phone
0    A   m  010-3126-9994
1    B   f  010-6523-1786
2    C   f  010-0620-0210


In [8]:
# 판다스는 데이터프레임에서 원하는 구간만 조회가 가능

print(pd_dataframe_3.head(2))

print(pd_dataframe_3.tail(2))

print(pd_dataframe_3["sex"])

  name sex          phone
0    A   m  010-3126-9994
1    B   f  010-6523-1786
  name sex          phone
1    B   f  010-6523-1786
2    C   f  010-0620-0210
0    m
1    f
2    f
Name: sex, dtype: object


판다스는 데이터를 데이터프레임으로 생성할 수 있지만 외부의 데이터파일(csv,text,Excel,SQL,JSON)을 읽어서 데이터프레임으로 생성할 수 있다
csv_data = pd.read_csv("/경로.csv") 

In [9]:
import numpy as np  # 배열 

np_array_1=np.array([1,2,3,4,5])
print(np_array_1)   #행렬형태 => 연산가능

[1 2 3 4 5]


In [10]:
np_array_2=np.array([[1,2,3],[4,5,6]])  

print(np_array_2)

[[1 2 3]
 [4 5 6]]


In [11]:
print("array_1 data type:",type(np_array_1))
print("arrya_2 data type:",type(np_array_2))

array_1 data type: <class 'numpy.ndarray'>
arrya_2 data type: <class 'numpy.ndarray'>


In [12]:
print("array1 축의 개수 :",np_array_1.ndim)
print("array1 의 크기:",np_array_1.shape)

array1 축의 개수 : 1
array1 의 크기: (5,)


In [13]:
zero_array=np.zeros((3,3))
print(zero_array)  #영행렬

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
one_array=np.ones((2,3))
print(one_array)  #모든 원소 값이 1인 배열

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
full_array=np.full((3,4),5)
print(full_array)   # 모든 원소의 값을 지정한 값으로 

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
eye_array=np.eye(3)
print(eye_array)  #단위행렬

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
random_array=np.random.random((2,2))   #random.random 랜덤의 종류가 다양하기 때문
print(random_array) #1보다 작은 숫자만

[[0.0142224  0.50086836]
 [0.96848889 0.68479489]]


In [24]:
random_array[0][0]

0.014222396903502021

In [19]:
arange_array=np.arange(10)
print(arange_array)   #0부터 n-1까지의 원소 값을 가지는 배열 생성 

[0 1 2 3 4 5 6 7 8 9]


In [20]:
arange_array_2=np.arange(1,20,2)
print(arange_array_2)   #arange(i,j,k)는 i부터 시작해서 j-1까지 k씩 증가하는 배열 :for문

[ 1  3  5  7  9 11 13 15 17 19]


In [21]:
arange_array_3=np.arange(30)
reshape_array=arange_array_3.reshape((5,6))

print(reshape_array)  #배열 내부의 데이터는 변경하지 않고 배열의 구조를 변경 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [22]:
x = np.array([1,2,3])
y = np.array([4,5,6])

result = x+y
result2= np.add(x,y)

print(result)
print(result2)   #두 가지 방식 

[5 7 9]
[5 7 9]


In [23]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

result = np.dot(x,y)
z = x@y   #행렬 곱 함수형태와 연산자 형태 

print(result)
print(z)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
